### ISSUE TITLE
Kathara check/lstart/vstart fails when there is no startup file

### ISSUE THREAD

**Issue by lara29** [KatharaFramework/Kathara#112]
**Describe the bug**
With the latest code, the check command and lstart fails when the lab folder contains no startup file

**To Reproduce**
Run either the check command, or the lstart command with just lab.conf (no other files in the lab folder)

**Expected behavior**
Kathara brings up containers even in the absence of startup files

**Logs**
ERROR - 	! Running `Hello World` failed: object of type 'NoneType' has no len()
Traceback (most recent call last):
  File "/root/Kathara/src/Resources/cli/command/CheckCommand.py", line 60, in run
    ManagerProxy.get_instance().deploy_lab(lab)
  File "/root/Kathara/src/Resources/manager/ManagerProxy.py", line 31, in deploy_lab
    self.manager.deploy_lab(lab, privileged_mode)
  File "/root/Kathara/src/Resources/manager/kubernetes/KubernetesManager.py", line 38, in deploy_lab
    self.k8s_machine.deploy_machines(lab, privileged_mode)
  File "/root/Kathara/src/Resources/manager/kubernetes/KubernetesMachine.py", line 142, in deploy_machines
    iterable=chunk
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 266, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/root/Kathara/src/Resources/manager/kubernetes/KubernetesMachine.py", line 154, in _deploy_machine
    self.create(machine)
  File "/root/Kathara/src/Resources/manager/kubernetes/KubernetesMachine.py", line 190, in create
    config_map = self.kubernetes_config_map.deploy_for_machine(machine)
  File "/root/Kathara/src/Resources/manager/kubernetes/KubernetesConfigMap.py", line 18, in deploy_for_machine
    config_map = self._build_for_machine(machine)
  File "/root/Kathara/src/Resources/manager/kubernetes/KubernetesConfigMap.py", line 39, in _build_for_machine
    tar_data_size = len(tar_data)
TypeError: object of type 'NoneType' has no len()

**Analysis**
I did some digging on my own and the offensive portion is the line https://github.com/KatharaFramework/Kathara/blob/ef5f225a9f6fee790a44182d61f02105190a6f18/src/Resources/manager/kubernetes/KubernetesConfigMap.py#L37

Is this condition necessary, ie, we need a non empty startup file?

**Comment by Skazza94** [comment]
Hi @lara29,
thanks for reporting this issue! We just released the Kubernetes Manager, so it is possible that it contains some untracked bugs.

I solved the problem and I'm packing a new release (3.0.5) with the fix.
I'll update you when it is available.

Thanks!

**Comment by Skazza94** [comment]
Hi @lara29,
3.0.5 version is released and fixes this problem. If you have any other problem don't hesitate to open a new issue! 😄

**Comment by lara29** [comment]
Thanks @Skazzino for promptly getting this fixed :)
