### ISSUE TITLE
Error while checking Kathara

### ISSUE THREAD

**Issue by diogolopes18-cyber** [KatharaFramework/Kathara#114]
**Describe the bug**
While installing Kathara, after I sourced the shell file and running `kathara check` I get the following error:

File "/opt/Kathara/src/Resources/foundation/factory/Factory.py", line 19, in get_class
    return class_for_name(module_name, class_name)
  File "/opt/Kathara/src/Resources/utils.py", line 39, in class_for_name
    m = importlib.import_module(module_name + "." + class_name)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/Kathara/src/Resources/manager/docker/DockerManager.py", line 3, in <module>
    import docker
ModuleNotFoundError: No module named 'docker'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/Kathara/src/kathara.py", line 112, in <module>
    KatharaEntryPoint()
  File "/opt/Kathara/src/kathara.py", line 67, in __init__
    Setting.get_instance().check()
  File "/opt/Kathara/src/Resources/setting/Setting.py", line 123, in check
    self.check_manager()
  File "/opt/Kathara/src/Resources/setting/Setting.py", line 168, in check_manager
    managers = ManagerProxy.get_available_managers_name()
  File "/opt/Kathara/src/Resources/manager/ManagerProxy.py", line 73, in get_available_managers_name
    class_args=(manager_name.capitalize(), )
  File "/opt/Kathara/src/Resources/foundation/factory/Factory.py", line 24, in get_class
    raise ImportError from e
ImportError
![kathara_error_1](https://user-images.githubusercontent.com/57946086/100515681-c7ec0300-3175-11eb-8998-7ed7473c34d7.png)

I've checked and I have Docker installed.

**Comment by Skazza94** [comment]
Hi @diogolopes18-cyber,
before using Kathará from source code, you should install pip dependencies. 

To do so, from a Terminal, go into `src` and type
```sudo python3 -m pip install -r requirements.txt```

After this, Kathará should work fine.

**Comment by diogolopes18-cyber** [comment]
It worked, thanks!
